# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duct_model.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 525)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 621, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_ariel_logo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_ariel_logo.setText("")
        self.label_ariel_logo.setPixmap(QtGui.QPixmap("../../ARIEL Precision Medicine Part-Time Work/Digital Assets and Templates/ARIEL_Logo_RGB_100px.png"))
        self.label_ariel_logo.setScaledContents(False)
        self.label_ariel_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ariel_logo.setObjectName("label_ariel_logo")
        self.verticalLayout_3.addWidget(self.label_ariel_logo)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.patient_variants = QtWidgets.QWidget()
        self.patient_variants.setObjectName("patient_variants")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.patient_variants)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 601, 381))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_variant_input_area = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_variant_input_area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variant_input_area.setObjectName("label_variant_input_area")
        self.verticalLayout.addWidget(self.label_variant_input_area)
        self.comboBox_variant_input_area = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_variant_input_area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_variant_input_area.setFrame(True)
        self.comboBox_variant_input_area.setModelColumn(0)
        self.comboBox_variant_input_area.setObjectName("comboBox_variant_input_area")
        self.verticalLayout.addWidget(self.comboBox_variant_input_area)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add_variant = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_add_variant.setAutoFillBackground(False)
        self.pushButton_add_variant.setStyleSheet("")
        self.pushButton_add_variant.setAutoDefault(False)
        self.pushButton_add_variant.setFlat(False)
        self.pushButton_add_variant.setObjectName("pushButton_add_variant")
        self.horizontalLayout.addWidget(self.pushButton_add_variant)
        self.pushButton_remove_variant = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_remove_variant.setObjectName("pushButton_remove_variant")
        self.horizontalLayout.addWidget(self.pushButton_remove_variant)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_wt_functionality = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_wt_functionality.setObjectName("label_wt_functionality")
        self.verticalLayout.addWidget(self.label_wt_functionality)
        self.progressBar_wt_functionality = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar_wt_functionality.setProperty("value", 100)
        self.progressBar_wt_functionality.setObjectName("progressBar_wt_functionality")
        self.verticalLayout.addWidget(self.progressBar_wt_functionality)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_load_variants = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_load_variants.setObjectName("pushButton_load_variants")
        self.verticalLayout.addWidget(self.pushButton_load_variants)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.plainTextEdit_patient_variants = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.plainTextEdit_patient_variants.setReadOnly(True)
        self.plainTextEdit_patient_variants.setObjectName("plainTextEdit_patient_variants")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_patient_variants)
        self.tabWidget.addTab(self.patient_variants, "")
        self.model_inputs = QtWidgets.QWidget()
        self.model_inputs.setObjectName("model_inputs")
        self.gridLayoutWidget = QtWidgets.QWidget(self.model_inputs)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 349, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 40, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_antiporter_on = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_antiporter_on.setObjectName("radioButton_antiporter_on")
        self.horizontalLayout_3.addWidget(self.radioButton_antiporter_on)
        self.radioButton_antiporter_off = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_antiporter_off.setObjectName("radioButton_antiporter_off")
        self.horizontalLayout_3.addWidget(self.radioButton_antiporter_off)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.label_trigger_update = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_trigger_update.setObjectName("label_trigger_update")
        self.gridLayout.addWidget(self.label_trigger_update, 6, 0, 1, 1)
        self.label_intra_hco3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_hco3.setObjectName("label_intra_hco3")
        self.gridLayout.addWidget(self.label_intra_hco3, 1, 0, 1, 1)
        self.pushButton_trigger_update = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_trigger_update.setObjectName("pushButton_trigger_update")
        self.gridLayout.addWidget(self.pushButton_trigger_update, 6, 1, 1, 1)
        self.label_intra_cl_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_cl_2.setObjectName("label_intra_cl_2")
        self.gridLayout.addWidget(self.label_intra_cl_2, 3, 2, 1, 1)
        self.horizontalSlider_lum_hco3 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_lum_hco3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lum_hco3.setObjectName("horizontalSlider_lum_hco3")
        self.gridLayout.addWidget(self.horizontalSlider_lum_hco3, 2, 1, 1, 1)
        self.label_intra_na = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_na.setObjectName("label_intra_na")
        self.gridLayout.addWidget(self.label_intra_na, 4, 0, 1, 1)
        self.label_lum_hco3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_lum_hco3.setObjectName("label_lum_hco3")
        self.gridLayout.addWidget(self.label_lum_hco3, 2, 0, 1, 1)
        self.horizontalSlider_intra_cl = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_intra_cl.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_intra_cl.setObjectName("horizontalSlider_intra_cl")
        self.gridLayout.addWidget(self.horizontalSlider_intra_cl, 3, 1, 1, 1)
        self.horizontalSlider_intra_na = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_intra_na.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_intra_na.setObjectName("horizontalSlider_intra_na")
        self.gridLayout.addWidget(self.horizontalSlider_intra_na, 4, 1, 1, 1)
        self.label_intra_na_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_na_value.setObjectName("label_intra_na_value")
        self.gridLayout.addWidget(self.label_intra_na_value, 4, 2, 1, 1)
        self.label_intra_cl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_cl.setObjectName("label_intra_cl")
        self.gridLayout.addWidget(self.label_intra_cl, 3, 0, 1, 1)
        self.label_antiporters = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_antiporters.setObjectName("label_antiporters")
        self.gridLayout.addWidget(self.label_antiporters, 0, 0, 1, 1)
        self.label_intra_hco3_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_intra_hco3_value.setObjectName("label_intra_hco3_value")
        self.gridLayout.addWidget(self.label_intra_hco3_value, 1, 2, 1, 1)
        self.label_lum_hco3_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_lum_hco3_value.setObjectName("label_lum_hco3_value")
        self.gridLayout.addWidget(self.label_lum_hco3_value, 2, 2, 1, 1)
        self.horizontalSlider_intra_hco3 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_intra_hco3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_intra_hco3.setObjectName("horizontalSlider_intra_hco3")
        self.gridLayout.addWidget(self.horizontalSlider_intra_hco3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 2, 1, 1)
        self.tabWidget.addTab(self.model_inputs, "")
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.graph)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 611, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.matplotlibWidget = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.matplotlibWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.matplotlibWidget.setObjectName("matplotlibWidget")
        self.verticalLayout_4.addWidget(self.matplotlibWidget)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.graph, "")
        self.clinical_suggestions = QtWidgets.QWidget()
        self.clinical_suggestions.setObjectName("clinical_suggestions")
        self.plainTextEdit_clinical_suggestions = QtWidgets.QPlainTextEdit(self.clinical_suggestions)
        self.plainTextEdit_clinical_suggestions.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.plainTextEdit_clinical_suggestions.setObjectName("plainTextEdit_clinical_suggestions")
        self.tabWidget.addTab(self.clinical_suggestions, "")
        self.acinar_model = QtWidgets.QWidget()
        self.acinar_model.setObjectName("acinar_model")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.acinar_model)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(50, 30, 631, 321))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../../../Desktop/1-s2.0-S1357272505004085-gr1.gif"))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.tabWidget.addTab(self.acinar_model, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_variant_input_area.setText(_translate("MainWindow", "Variant Input Area"))
        self.pushButton_add_variant.setToolTip(_translate("MainWindow", "Add Variant to List"))
        self.pushButton_add_variant.setText(_translate("MainWindow", "Add"))
        self.pushButton_remove_variant.setToolTip(_translate("MainWindow", "Remove variant from list"))
        self.pushButton_remove_variant.setText(_translate("MainWindow", "Remove"))
        self.label_wt_functionality.setText(_translate("MainWindow", "% WT Functionality"))
        self.pushButton_load_variants.setText(_translate("MainWindow", "Load Variants into Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.patient_variants), _translate("MainWindow", "Patient Variants"))
        self.radioButton_antiporter_on.setText(_translate("MainWindow", "On"))
        self.radioButton_antiporter_off.setText(_translate("MainWindow", "Off"))
        self.label_trigger_update.setText(_translate("MainWindow", "Trigger Update"))
        self.label_intra_hco3.setText(_translate("MainWindow", "Intracellular HCO3-"))
        self.pushButton_trigger_update.setText(_translate("MainWindow", "Update"))
        self.label_intra_cl_2.setText(_translate("MainWindow", "default_cl"))
        self.label_intra_na.setText(_translate("MainWindow", "Intracellular Na+"))
        self.label_lum_hco3.setText(_translate("MainWindow", "Luminal HCO3-"))
        self.label_intra_na_value.setText(_translate("MainWindow", "default_na"))
        self.label_intra_cl.setText(_translate("MainWindow", "Intracellular Cl-"))
        self.label_antiporters.setText(_translate("MainWindow", "Antiporters"))
        self.label_intra_hco3_value.setText(_translate("MainWindow", "default_bi"))
        self.label_lum_hco3_value.setText(_translate("MainWindow", "default_bl"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_inputs), _translate("MainWindow", "Model Inputs"))
        self.label_4.setText(_translate("MainWindow", "Bicarbonate Secretion in Duct Cell Graph"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graph), _translate("MainWindow", "HCO3(−) Secretion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clinical_suggestions), _translate("MainWindow", "Clinical Suggestions"))
        self.label_15.setText(_translate("MainWindow", "Placeholder Image, Source: https://ars.els-cdn.com/content/image/1-s2.0-S1357272505004085-gr1.gif"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acinar_model), _translate("MainWindow", "Acinar Cell Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

